language: python
python:
  - "2.7"
env:
  - DJANGO=1.6
  - DJANGO=1.7
  - DJANGO=1.8
install:
  - pip install pip -U
  - pip install -q Django==$DJANGO
  - pip install pep8 -U
  - pip install pyflakes -U
  - pip install coveralls -U
before_script:
  - "pep8 --exclude=migrations modular_blocks"
  - pyflakes modular_blocks
script:
  - coverage run --source=modular_blocks manage.py test
after_success:
  - coveralls
